name: rogers_dictionary
description: The electronic version of Dr Rogers Spanish Medical Dictionary.

publish_to: 'none'

version: 1.0.4+15

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  animations: ^2.0.0
  async: ^2.8.1
  async_list_view: ^1.0.0
  cupertino_icons: ^1.0.3
  feedback:
    path: ../feedback/feedback
  firebase_analytics: ^9.0.4
  firebase_core: ^1.1.0
  firebase_crashlytics: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.0.0
  google_mobile_ads: ^1.0.0
  http: ^0.13.3
  implicit_navigator:
    path: ../implicit_navigator
  just_audio: ^0.9.7
  package_info: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  sqflite: ^2.0.0+3

dev_dependencies:
  df: ^0.4.0-nullsafety.0
  firedart: ^0.9.0+1
  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.2
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.0.1+1
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  msix: ^2.1.3
  screenshot: ^1.2.3
  sqflite_common_ffi: ^2.0.0
  test: ^1.19.5
  device_frame: ^1.0.0
  image: ^3.1.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/glenn.jpg
    - assets/

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_android: "assets/images/n_logo_flat.png"
  image_path_ios: "assets/images/n_logo_ios.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/n_logo_foreground.png"

flutter_native_splash:
  color: "ffffff"
  branding: "assets/images/n_logo_splash.png"
  android_gravity: top
  ios_content_mode: center

msix_config:
  display_name: Rogers Dictionary
  publisher_display_name: Rogers Dictionary
  identity_name: com.rogers.dictionary
  msix_version: 0.0.1.0
  certificate_path: C:\Users\Waffl\Documents\code\rogers_dictionary\keys\not_a_virus.pfx
  certificate_password: notavirus
  publisher: E=caseycrogers@berkeley.edu, CN=Rogers Dictionary, O=Rogers Dictionary, L=Willits, S=California, C=US
  architecture: x64
